<<<<<<< HEAD
image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  script:
    - echo "Building the Docker image for the Flask app"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ./app
  artifacts:
    paths:
      - app/

# Test Stage
test:
  stage: test
  script:
    - echo "Running tests on the Flask app"
    - docker run --rm $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME pytest

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying the Flask app"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo "Deployed successfully!"
  only:
    - main
=======
stages:
  - build
  - test
  - deploy_staging
  - deploy_production

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  script:
    - echo "No tests defined"

deploy_staging:
  stage: deploy_staging
  script:
    - echo "Deploy to staging"
    - docker run -d -p 5000:5000 $DOCKER_IMAGE

deploy_production:
  stage: deploy_production
  when: manual
  script:
    - echo "Deploy to production"
    - docker run -d -p 5000:5000 $DOCKER_IMAGE

>>>>>>> 678995e (Add CI/CD pipeline configuration)
