image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  script:
    - echo "Building the Docker image for the Flask app"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ./app
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - app/

# Test Stage
test:
  stage: test
  script:
    - echo "Running tests on the Flask app"
    - docker run --rm $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME pytest

# Deploy Stage
deploy:
  stage: deploy
  script:
    - echo "Deploying the Flask app"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo "Deployed successfully!"
  only:
    - main
