stages:
  - build
  - test
  - deploy_staging
  - deploy_production

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  script:
    - echo "No tests defined"

deploy_staging:
  stage: deploy_staging
  script:
    - echo "Deploy to staging"
    - docker run -d -p 5000:5000 $DOCKER_IMAGE

deploy_production:
  stage: deploy_production
  when: manual
  script:
    - echo "Deploy to production"
    - docker run -d -p 5000:5000 $DOCKER_IMAGE

